



<table border="1">
<?

$viewer=$this->planeViewer;
$viewer->reset();
$path=$this->getScriptPaths();
$path=$path[0];

$viewer->setTileScript($path."admin/sectortile.phtml");
while($viewer->moreY()){$viewer->resetX();?>
	<tr>
	<?while($viewer->moreX()){?>
		<td>
		<?$viewer->render()?>
		</td>
	<?}?>
	</tr>
<?}?>
</table>
<form method="POST" action="/admin/showPlane">
<input type="submit" value="Zoom To:" /> 
<input type="text" name="zoomX" value="<?=$_POST['zoomX']?>" />
<input type="text" name="zoomY" value="<?=$_POST['zoomY']?>" />
Zoom Amount:<input type="text" name="zoom" value="<?=$_POST['zoom']?>" />
</form>