<div style="width:30px;height:23px">
<center>

<?
if($this->y > $this->center->longitude())$buf.= "S";
if($this->y < $this->center->longitude())$buf.= "N";
if($this->x < $this->center->latitude())$buf.= "W";
if($this->x > $this->center->latitude())$buf.= "E";
 ?>
  <?
$sector=$this->getCurrentSector();
if(($this->getCurrentSector()!=$this->emptySector || $this->plane->generic_sector_id) && ($this->x!=$this->center->latitude() || $this->y!=$this->center->longitude())){
	$link=true;?>
	<input type="submit" value="<?=$buf?>" onclick="redirect('/play/move?l=<?=$buf?>')" style="width:30px;height:23px"/>
<?}else{?>
	<input type="submit" value="<?=$buf?>" disabled style="width:30px;height:23px" />

<?}?>
 </center>
</div>